### ISSUE TITLE
POST not allowed when uploading key

### ISSUE THREAD

**Issue by grillazz** [samuelcolvin/aioaws#22]
Getting below error when trying upload file. 

```bash
root@b4cf3fba168e:/app# python main.py
[S3File(key='test.txt', last_modified=datetime.datetime(2021, 10, 25, 12, 5, 32, 928000, tzinfo=datetime.timezone.utc), size=282, e_tag='9e36cc3537ee9ee1e3b10fa4e761045b', storage_class='STANDARD'),]
Traceback (most recent call last):
  File "/app/main.py", line 78, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/main.py", line 76, in main
    await s3_demo(client)
  File "/app/main.py", line 18, in s3_demo
    await s3.upload('test/upload-to.txt',b'test')
  File "/usr/local/lib/python3.9/site-packages/aioaws/s3.py", line 111, in upload
    await self._aws_client.raw_post(d['url'], expected_status=204, data=d['fields'], files={'file': content})
  File "/usr/local/lib/python3.9/site-packages/aioaws/core.py", line 69, in raw_post
    raise RequestError(r)
aioaws.core.RequestError: unexpected response from POST "https://host.net/mybucket/": 403, response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Policy check failed, variable not met condition: bucket</Message><BucketName>mybucket</BucketName><RequestId>tx000000000000003fdf954-0061769dea-342945885-default</RequestId><HostId>342945885-default-d
efault</HostId></Error>
```

I was able to list as you can find above but not add file to bucket.

Additionally I can add files with aws cli onto this uri / bucket

**Comment by scebotari** [comment]
Hi @samuelcolvin ,

First of all thanks for this SDK. It's really lightweight, easy to use and solves all the needs on current project.

But the issues described by @grillazz affects my use case too, because of the dot in the bucket name.

Currently I'm using a workaround provided by you in [this comment](https://github.com/samuelcolvin/aioaws/issues/22#issuecomment-950957600) and it work fine. But would be nice to have support for bucket names containing dots, since they are valid and accepted by AWS S3.

I'm willing to make a PR that fixes this issue. Just wanted to clarify what you meant by `create a PR here to make use_custom_bucket_domains an option`.

Should I add one more field to `S3Config` called `use_custom_bucket_domains` and implement next logic?

```
  bucket = get_config_attr(config, 'aws_s3_bucket')
  use_custom_bucket_domains = get_config_attr(config, 'use_custom_bucket_domains')
  if use_custom_bucket_domains and '.' in bucket:
     # assumes the bucket is a domain and is already as a CNAME record for S3 
     self.host = bucket 
 else: 
     # see https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html 
     self.host = f'{bucket}.s3.{self.region}.amazonaws.com' 
```
